indexMappings:
  - https://lschema.org/attributeName 
  - https://lschema.org/attributeIndex 
  - https://lschema.org/attributeValue 
  - https://lschema.org/entityId 
  - https://lschema.org/entityIdFields
  - https://lschema.org/nodeId 
  - https://lschema.org/schemaNodeId 
  - https://lschema.org/edgeLabel 
  - https://lschema.org/entitySchema 
  - https://lschema.org/xml/ns 
  - https://lschema.org/conditional 