indexMappings:
  https://lschema.org/attributeName: 1
  https://lschema.org/attributeIndex: 2
  https://lschema.org/attributeValue: 3
  https://lschema.org/entityId: 4
  https://lschema.org/entityIdFields: 5
  https://lschema.org/nodeId: 6
  https://lschema.org/schemaNodeId: 7
  https://lschema.org/edgeLabel: 8
  https://lschema.org/entitySchema: 9
  https://lschema.org/xml/ns: 10
  https://lschema.org/conditional: 11