baseURL: "http://example.org/"
languageCode: "en-us"
title: "Layered Schemas"
# We disable taxonomies because we don't provide templates for them, and they
# don't apply to our minimal use case.
disableKinds:
  - taxonomy
  - taxonomyTerm
disablePathToLower: true

params:
  copyright: © Cloud Privacy Labs 2022
  
markup:
  goldmark:
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false

menu:
  main:
    - identifier: home
      title: Home
      weight: 1
      url: /
    - identifier: docs
      title: Docs
      weight: 2
      url: /docs
    - identifier: source
      title: Source
      weight: 3
      url: https://github.com/cloudprivacylabs/lsa
