baseURL = "http://lschema.org/"
languageCode = "en-us"
title = "Layered Schema Architecture"
# We disable taxonomies because we don't provide templates for them, and they
# don't apply to our minimal use case.
disableKinds = ["taxonomy", "taxonomyTerm"]
disablePathToLower = true
