baseURL = "http://example.org/"
languageCode = "en-us"
title = "Hugo Skeleton"
# We disable taxonomies because we don't provide templates for them, and they
# don't apply to our minimal use case.
disableKinds = ["taxonomy", "taxonomyTerm"]
disablePathToLower = true

[params]
copyright = "© Cloud Privacy Labs 2022"

[markup.goldmark.renderer]
    hardWraps = false
    unsafe = true
    xhtml = false